dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: infrastructure
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.2.0
- name: rabbitmq
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.8.0
- name: ttc-connectors-processing
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.26
- name: ttc-connectors-ranking
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.29
- name: ttc-connectors-reward
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.20
- name: ttc-dashboard-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.38
- name: ttc-query-campaign
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.30
- name: ttc-rb-english-campaign
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.10
